#!/bin/sh
# Assert the husky gate shim is live in a worktree (worktree G1 — fail-closed).
#
# The husky wrappers (.husky/_/) are gitignored and regenerated by `npm install`.
# If a worktree has committed hooks (.husky/pre-commit, .husky/pre-push, ...) but no
# matching wrapper (.husky/_/<hook>), the pre-commit/pre-push GATES SILENTLY DO NOT
# RUN — a fail-open that voids the whole review boundary. This asserts every committed
# hook has its wrapper. Exit 1 if any is missing; exit 0 otherwise (incl. projects
# that use neither npm nor husky — nothing to assert).
#
# Usage: scripts/assert-husky-shim.sh <worktree-dir>
DIR="${1:?Usage: assert-husky-shim.sh <worktree-dir>}"

[ -f "$DIR/package.json" ] || exit 0   # not an npm project
[ -d "$DIR/.husky" ] || exit 0         # project does not use husky

missing=""
for hook in "$DIR"/.husky/*; do
  [ -f "$hook" ] || continue           # skip the _/ dir and non-files
  name=$(basename "$hook")
  [ -f "$DIR/.husky/_/$name" ] || missing="$missing $name"
done

if [ -n "$missing" ]; then
  echo "assert-husky-shim: husky wrapper(s) missing in $DIR/.husky/_ for:$missing" >&2
  echo "  → the git gates would silently NOT run. Run 'npm install' to regenerate, or remove this worktree." >&2
  exit 1
fi
exit 0
